In [8]:
import numpy as np

print("this worked" )
import datetime


def greet(name):
    current_time = datetime.datetime.now().strftime("%H:%M:%S")
    print(f"[{current_time}] Hello, {name}!")


this worked


Just a test run


In [9]:
import numpy as np
def create_matrix(rows, cols):
    return np.random.rand(rows, cols)

def matrix_multiply(A, B):
    return np.dot(A, B)

def compute_statistics(matrix):
    return {
        "mean": np.mean(matrix),
        "std_dev": np.std(matrix),
        "min": np.min(matrix),
        "max": np.max(matrix),
        "sum": np.sum(matrix)
    }

def main():
    print("NumPy Dummy Project")

    A = create_matrix(3, 3)
    B = create_matrix(3, 3)

    print("\nMatrix A:")
    print(A)

    print("\nMatrix B:")
    print(B)

    C = matrix_multiply(A, B)

    print("\nA @ B:")
    print(C)

    stats = compute_statistics(C)

    print("\nStatistics of Result:")
    for key, value in stats.items():
        print(f"{key}: {value}")


if __name__ == "__main__":
    main()


NumPy Dummy Project

Matrix A:
[[0.25968928 0.94690829 0.3517714 ]
 [0.29143762 0.05650625 0.88847338]
 [0.92899771 0.08641351 0.04842176]]

Matrix B:
[[0.9093731  0.34207635 0.73405009]
 [0.77903842 0.35141686 0.69180794]
 [0.61072508 0.21353654 0.71651531]]

A @ B:
[[1.188668   0.49670915 1.0977532 ]
 [0.85165905 0.3092727  0.88962606]
 [0.94169735 0.35849512 0.77640733]]

Statistics of Result:
mean: 0.7678097739990419
std_dev: 0.29617099308424266
min: 0.3092726964299578
max: 1.188667997770041
sum: 6.910287965991378
